server:
  port: 8085
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_ADDRESS}/${MYSQL_SCHEMA}?characterEncoding=utf8&serverTimezone=GMT%2B8
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  mail:
    host: ${SMTP_HOST}
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
          auth: true
          starttls:
            enable: true
            required: true
    jndi-name: mail/Session
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    default-encoding: UTF-8

mail:
  domain: ${MAIL_DOMAIN}
  from: ${spring.mail.username}@${mail.domain}

mybatis-plus:
  type-enums-package: package top.horizonask.hoawiki.authorization.entity
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler

jwt:
  issuer: hoawiki
  tokenHeader: Authorization
  tokenPrefix: Bearer
  expiration: 86400
  antMatchers: /auth/user/login/**,/auth/user/register/**,/static/**,/message
